---
- hosts: all
  tasks:
    - name: ensure vim is installed and at the latest version
      yum: pkg=vim state=latest
      tags:
         - packages

    - name: ensure ack is installed at at the latest version
      yum: pkg=ack state=latest
      tags:
         - packages

    - name: set host name
      hostname: name={{inventory_hostname}}
      tags:
         - configuration

    - name: add standard groups
      group: name={{item}}
      with_items: std_groups
      tags:
         - users

    - name: add standard users
      user: name="{{item['name']}}" groups="{{item['groups']}}" password="{{item['password']}}"
      with_items: users
      tags:
         - users
