---
- hosts: webservers
  tasks:
    - name: ensure apache is installed and is the latest version
      yum: pkg=httpd state=latest
      tags:
         - packages
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
